name: build and test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build and Test default scheme using any available iPhone simulator
    runs-on: macos-latest
    env:
      platform: ${{ 'iOS Simulator' }}
      device: iPhone 11 Pro
      scheme: AcceptanceTests
      project: EncryptCardTests.xcodeproj

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with: 
          submodules: recursive
      - name: Resolve dependencies
        run: xcodebuild -resolvePackageDependencies -project $project -scheme $scheme
      - name: Test
        uses: sersoft-gmbh/xcodebuild-action@v1
        with:
          project: $project
          scheme: $scheme
          destination: platform=iOS Simulator,name=iPhone 11 Pro
          action: test
